// <auto-generated />
namespace OMoney.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RefreshTokens_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefreshTokens_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201506091416580_RefreshTokens_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
