// <auto-generated />
namespace OMoney.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class naming_and_activity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(naming_and_activity));
        
        string IMigrationMetadata.Id
        {
            get { return "201502181246314_naming_and_activity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
